name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  develop-pr-job:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Lint HTML and CSS Files
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"

      - name: Build Static Website
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
